spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/play
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    enabled: true